
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compiler.cparser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int STRING_LITERAL = 36;
  public static final int CHAR = 5;
  public static final int CHAR_LITERAL = 39;
  public static final int GE = 13;
  public static final int SEMI = 28;
  public static final int INT = 3;
  public static final int FOR = 10;
  public static final int MINUS = 19;
  public static final int NOT = 25;
  public static final int AND = 23;
  public static final int LT = 14;
  public static final int LP = 31;
  public static final int OR = 24;
  public static final int COMMA = 27;
  public static final int DIV = 21;
  public static final int RP = 32;
  public static final int PLUS = 18;
  public static final int ASSIGN = 11;
  public static final int IF = 7;
  public static final int ID = 35;
  public static final int DOT = 26;
  public static final int LE = 15;
  public static final int EOF = 0;
  public static final int LC = 33;
  public static final int LB = 29;
  public static final int RETURN = 6;
  public static final int error = 1;
  public static final int RC = 34;
  public static final int MUL = 20;
  public static final int RB = 30;
  public static final int MOD = 22;
  public static final int NEQ = 17;
  public static final int EQ = 16;
  public static final int ELSE = 8;
  public static final int WHILE = 9;
  public static final int FLOAT = 4;
  public static final int FLOAT_LITERAL = 38;
  public static final int STRUCT = 2;
  public static final int GT = 12;
  public static final int INT_LITERAL = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRUCT",
  "INT",
  "FLOAT",
  "CHAR",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "ASSIGN",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NEQ",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "DOT",
  "COMMA",
  "SEMI",
  "LB",
  "RB",
  "LP",
  "RP",
  "LC",
  "RC",
  "ID",
  "STRING_LITERAL",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "CHAR_LITERAL"
  };
}

